#!/bin/bash

xhost +
docker run -ti --rm --privileged --name fldigi \
            --device /dev/snd \
            -e PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native \
            -v ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native \
            -v ~/.config/pulse/cookie:/root/.config/pulse/cookie \
            --group-add $(getent group audio | cut -d: -f3) \
            -e DISPLAY=$DISPLAY \
            -v /tmp/.X11-unix:/tmp/.X11-unix \
            -v $HOME/.Xauthority:/root/.Xauthority \
              telegraphist/fldigi /bin/sh

